# Generated by Django 4.2.20 on 2025-04-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
