# Generated by Django 4.2.20 on 2025-04-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
